[build]
  command = "sh setup.sh && pnpm run build"
  publish = "packages/client/dist"

[build.environment]
  NODE_VERSION = "18"
  GO_VERSION = "1.17.x"
  PATH = "/opt/buildhome/.foundry/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH"

[context.production.environment]
  NODE_VERSION = "18"
  GO_VERSION = "1.17.x"
  PATH = "/opt/buildhome/.foundry/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH"

[context.deploy-preview]
  command = "sh setup.sh && pnpm run build"
  publish = "packages/client/dist"

[context.branch-deploy]
  command = "sh setup.sh && pnpm run build"
  publish = "packages/client/dist"
